### ISSUE TITLE
[Bug]: Error: spawn Unknown system error -86 on MacOS

### ISSUE THREAD

**Issue by racmve01** [NativePHP/electron#23]
### What happened?

<img width="1523" alt="Captura de pantalla 2023-07-21 a la(s) 10 03 06 p m" src="https://github.com/NativePHP/electron/assets/87492856/437b4439-5df4-437a-8db7-d9f4ab142d99">

### How to reproduce the bug

When running the artisan native php:serve gives the error...

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at execFile (node:child_process:359:17)
    at node:child_process:252:21
    at node:electron/js2c/asar_bundle:2:3130
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:47:69
    at Generator.next (<anonymous>)
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:4:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

API server started on port 4000

Starting PHP server... /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/resources/php artisan serve /Users/profile1/Documents/proyectos_laravel/nativephp

Making sure app folders are available

(node:12387) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at callPhp (/Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:53:38)
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:135:9
    at Generator.next (<anonymous>)
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:4:12)
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:118:45
    at new Promise (<anonymous>)
(Use `Electron --trace-warnings ...` to show where the warning was created)

(node:12387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

### Package Version

0.1.0

### PHP Version

8.1.9

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS

**Comment by mualiyu** [comment]
Copy `vendor/nativephp/php-bin/bin/mac/arm64/php` or `vendor/nativephp/php-bin/bin/mac/x86/php` (whichever one is for your macs architecture) to `vendor/nativephp/electron/resources/js/resources`

make sure to copy the right "php" file base on  your Macs architecture.

**Comment by mdloop** [comment]
This may be useful. For me, when I run `native:serve` it seems something copies over the best guess php binary into `.../js/resources`. So even if you do manually copy things over, the binary may be overwritten.

Running `php artisan native:serve --no-dependencies` worked for me.

In my case, it appears to think I need the x86 binary even though I'm using arm (m1).

**Comment by PhiloNL** [comment]
I solved it by running:

softwareupdate --install-rosetta

**Comment by mdloop** [comment]
> I solved it by running:
> 
> softwareupdate --install-rosetta

You are on intel or arm?

**Comment by PhiloNL** [comment]
> > I solved it by running:
> > 
> > softwareupdate --install-rosetta
> 
> You are on intel or arm?

Arm (M1)
