### ISSUE TITLE
[Bug]: MenuBar Feature not working

### ISSUE THREAD

**Issue by christophstockinger** [NativePHP/electron#38]
### What happened?

I created a new Laravel app and installed the package according to the tutorial. Then I tried to create a MenuBar application according to the doc. However, the icon is never displayed in the MenuBar.

### How to reproduce the bug

```php
// in the NativeAppServiceProvider
 MenuBar::create()
            ->width(400)
            ->height(400)
            ->alwaysOnTop()
            ->url('https://christophstockinger.com')
            ->label('Hallo')->open();
```

### Package Version

0.1.0

### PHP Version

8.2.6

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS

### Notes

Mac-Book Pro 14" - 2023
Apple M2 Max
macOs 13.2 (22D49)

**Comment by PierreThiollent** [comment]
I had this bug with 0.1 version and when updating to 0.1.1 the menu bar is now working

**Comment by mortenthogersen** [comment]
I have similiar issue

Package Version
**0.1.1**

PHP Version
8.2.6

Laravel Version
10.15.0

Which operating systems does with happen with?
macOS

Notes
Mac-Book Air M2
Apple M2
macOs 13.4 (22F66)

If i do

`
MenuBar::create()->showDockIcon();
`

If get these errors in terminal when clicking the dock icon:

```
(node:4823) electron: NSVisualEffectMaterialAppearanceBased has been deprecated and removed as of macOS 10.15.
(Use `Electron --trace-warnings ...` to show where the warning was created)

TypeError: Cannot read properties of undefined (reading 'webContents')
    at Menubar.<anonymous> (/Users/morten/code/NativePHP/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/api/menuBar.js:48:86)
    at Menubar.emit (node:events:513:28)
    at Menubar.<anonymous> (/Users/morten/code/NativePHP/vendor/nativephp/electron/resources/js/node_modules/menubar/lib/Menubar.js:370:30)
    at step (/Users/morten/code/NativePHP/vendor/nativephp/electron/resources/js/node_modules/menubar/lib/Menubar.js:59:23)
    at Object.next (/Users/morten/code/NativePHP/vendor/nativephp/electron/resources/js/node_modules/menubar/lib/Menubar.js:40:53)
    at fulfilled (/Users/morten/code/NativePHP/vendor/nativephp/electron/resources/js/node_modules/menubar/lib/Menubar.js:31:58)
```

**Comment by mpociot** [comment]
@mortenthogersen I'm unable to reproduce this
