### ISSUE TITLE
[Bug]: Command native:serve open electron-builder.js instead of running app

### ISSUE THREAD

**Issue by lepresk** [NativePHP/electron#49]
### What happened?

On Windows native:serve don't serve the app but it open electron-builder.js 
![Capture](https://github.com/NativePHP/electron/assets/10780686/7d92acab-f20f-4819-901e-d516b9462183)

### How to reproduce the bug

Create laravel app on windows
composer require nativephp/electron
php artisan native:install
php artisan native:serve

### Package Version

0.3.1

### PHP Version

8.1.12

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by pentiminax** [comment]
Same here

**Comment by mwakalingajohn** [comment]
Same here

**Comment by lepresk** [comment]
After a short debugging session, here's the real issue: it's actually the JavaScript development server (possibly Vite.js) that's crashing. I don't know the exact causes yet, but here's the stack trace.

![Capture](https://github.com/NativePHP/electron/assets/10780686/ee025253-c540-4a6b-8a81-33814356b1d7)

**Comment by lepresk** [comment]
After a short debugging session, here's the real issue: it's actually the JavaScript side :

```
error during start dev server and electron app:
Error: No electron app entry file found: D:\dev\web\native-php\vendor\nativephp\electron\resources\js\out\main\index.js
    at ensureElectronEntryFile (D:\dev\web\native-php\vendor\nativephp\electron\resources\js\node_modules\electron-vite\dist\chunks\lib-e45cc666.js:26:23)
    at Object.startElectron (D:\dev\web\native-php\vendor\nativephp\electron\resources\js\node_modules\electron-vite\dist\chunks\lib-e45cc666.js:120:5)
    at createServer (D:\dev\web\native-php\vendor\nativephp\electron\resources\js\node_modules\electron-vite\dist\chunks\lib-25a7a89c.js:74:21)
    at async CAC.<anonymous> (D:\dev\web\native-php\vendor\nativephp\electron\resources\js\node_modules\electron-vite\dist\cli.js:48:9)
```
![Capture](https://github.com/NativePHP/electron/assets/10780686/af7636e8-2955-469a-bdd1-091d739cf022)

**Comment by lepresk** [comment]
I was able to resolve the issue. You need to build at least once using `native:build win` before launching the development server `native:serve`

**Comment by drhoussem** [comment]
duplicate of #45

**Comment by lepresk** [comment]
https://github.com/NativePHP/electron/issues/49#issuecomment-1655613517

**Comment by lepresk** [comment]
To fix the issue : https://github.com/NativePHP/electron/issues/49#issuecomment-1655618904
